workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 12000
        instance_type: mac_mini_m1
scripts:
    
  - name: Build Android release
    script: | 
      while true; do echo hi;done
